declare module 'react-native-linear-gradient';
declare module 'react-native-sound';
declare module 'react-native-linear-gradient';
declare module 'react-native-haptic-feedback';
declare module 'react-native-maps';
declare module 'lottie-react-native';
declare module 'react-native-pager-view';
declare module 'expo-secure-store';
declare module 'expo-speech';
