require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'

target 'JARS' do
  use_frameworks!
  use_react_native!(:path => config[:reactNativePath])

  # Your existing pods (preserve everything)
  pod 'Stripe', '~> 26.0.0'
  pod 'BVLinearGradient'
  pod 'RNCAsyncStorage'
  pod 'RNCMaskedView'
  pod 'RNDateTimePicker'
  pod 'RNFBAnalytics'
  pod 'RNFBApp'
  pod 'RNFBAuth'
  pod 'RNFBMessaging'
  pod 'RNGestureHandler'
  pod 'RNReactNativeHapticFeedback'
  pod 'RNReanimated'
  pod 'RNSVG'
  pod 'RNScreens'
  pod 'RNSentry'
  pod 'lottie-react-native'
  pod 'react-native-maps'
  pod 'react-native-netinfo'
  pod 'react-native-pager-view'
  pod 'react-native-render-html'
  pod 'react-native-safe-area-context'
  pod 'react-native-slider'
  pod 'react-native-webview'
end

# --- MERGED post_install block ---
post_install do |installer|
  # React Native post-install (mandatory)
  react_native_post_install(installer)

  # Custom tweaks for Stripe
  installer.pods_project.targets.each do |target|
    if target.name == 'Stripe'
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end

  # Optional tweaks for RN modules (Sentry, Reanimated)
  installer.pods_project.targets.each do |target|
    if ['RNSentry','RNReanimated'].include?(target.name)
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
# --- END merged post_install ---
        config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
      end
    end
  end

  # Common safe defaults
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
# --- END merged post_install ---
