name: Lint & Format Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-format:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max-old-space-size=4096'

    steps:
      - uses: actions/checkout@v4

      - name: 🔍 Preflight - Verify lockfiles exist
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            echo '❌ Detected npm lockfile. Project is Yarn-only.'
            exit 1
          fi

          if [ ! -f yarn.lock ]; then
            echo '❌ Missing yarn.lock. Cannot guarantee reproducible installs.'
            exit 1
          fi

          echo '✅ Yarn lockfile verified.'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.4'
          cache: 'yarn'
          cache-dependency-path: |
            yarn.lock

      - name: Install dependencies (Yarn)
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Format
        run: yarn format:ci
