name: Lint & Format Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format
